# Generated by Django 3.1 on 2020-09-07 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('coursename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
