# Generated by Django 3.1 on 2020-09-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('courseuid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='root.course')),
                ('useruid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='root.users')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentid', models.IntegerField()),
                ('contentheading', models.CharField(max_length=100)),
                ('contentbody', models.TextField()),
                ('contenturl', models.TextField()),
                ('coursename', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cname', to='root.course')),
                ('courseuid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cuid', to='root.course')),
            ],
            options={
                'db_table': 'content',
            },
        ),
    ]
