# Generated by Django 3.1 on 2020-09-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_content_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='coursename',
        ),
        migrations.AlterField(
            model_name='content',
            name='courseuid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='root.course'),
        ),
    ]
